//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeVanHoang2210900024_Demo_OnTap.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LeVanHoang2210900024_Demo_OnTapEntities : DbContext
    {
        public LeVanHoang2210900024_Demo_OnTapEntities()
            : base("name=LeVanHoang2210900024_Demo_OnTapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LVH_SACH> LVH_SACH { get; set; }
        public virtual DbSet<LVH_TACGIA> LVH_TACGIA { get; set; }
    }
}
