//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeVanHoang2210900024_Demo_OnTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LVH_TACGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LVH_TACGIA()
        {
            this.LVH_SACH = new HashSet<LVH_SACH>();
        }
        
        public string Lvh_MaTG { get; set; }
        
        public string Lvh_TenTacGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LVH_SACH> LVH_SACH { get; set; }
    }
}
