//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeVanHoang2210900024_Demo_OnTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LVH_SACH
    {
        public string Lvh_MaSach { get; set; }
        public string Lvh_TenSach { get; set; }
        public Nullable<int> Lvh_SoTrang { get; set; }
        public Nullable<int> Lvh_NamXB { get; set; }
        public string Lvh_MaTG { get; set; }
        public Nullable<bool> Lvh_TrangThai { get; set; }
    
        public virtual LVH_TACGIA LVH_TACGIA { get; set; }
    }
}
