//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LvhK22CNT3Lesson11_2210900024.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LvhK22CNT3Lesson11DbEntities : DbContext
    {
        public LvhK22CNT3Lesson11DbEntities()
            : base("name=LvhK22CNT3Lesson11DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LvhCategory> LvhCategories { get; set; }
        public virtual DbSet<LvhProduct> LvhProducts { get; set; }
    }
}
