//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LvhK22CNT3Lesson11_2210900024.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LvhCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LvhCategory()
        {
            this.LvhProducts = new HashSet<LvhProduct>();
        }
        [Display(Name="Mã danh mục")]
    
        public int LvhID { get; set; }
        [Display(Name = "Tên danh mục")]
        public string LvhCateName { get; set; }
        [Display(Name = "Trạng thái")]
        public Nullable<bool> LvhStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LvhProduct> LvhProducts { get; set; }
    }
}
