//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LvhK22CNT3Lesson11_2210900024.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LvhProduct
    {
        public string LvhId2210900024 { get; set; }
        public string LvhProName { get; set; }
        public Nullable<int> LvhQty { get; set; }
        public Nullable<double> LvhPrice { get; set; }
        public Nullable<int> LvhCateId { get; set; }
        public Nullable<bool> LvhActive { get; set; }
    
        public virtual LvhCategory LvhCategory { get; set; }
    }
}
