//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LvhK22CNT3Lesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LvhAccount
    {
        public int LvhId { get; set; }
        public string LvhUserName { get; set; }
        public string LvhPassword { get; set; }
        public string LvhFullName { get; set; }
        public string LvhEmail { get; set; }
        public string LvhPhone { get; set; }
        public Nullable<bool> LvhActive { get; set; }
    }
}
